### ISSUE TITLE
Vyházet z GITu nepotřebné soubory

### ISSUE THREAD

**Issue by fan1x** [JanKleprlik/Zeleznice#1]
Do GITu se typicky dávají pouze zdrojové soubory + projektové soubory. Objektovké/zkompilované soubory se sem nedávají

**Comment by JanKleprlik** [comment]
hotovo, smazal jsem všechno a nechal pouze .pas a dokumentaci

**Comment by fan1x** [comment]
Teď jsi toho vyházel moc.. :) Ideální je nechat zdrojové soubory a projektové soubory (v případě lazaruse například *.lpi). Chceš dosáhnout stavu, aby když si jiný uživatel vyclonuje tvůj projekt z GITu a má stejné vývojové prostředí, tak jen otevřene projektový soubor a všechno hned funguje...

**Comment by JanKleprlik** [comment]
To dává rozum :). Předělal jsem to, teď by to mělo být v pořádku.
