### ISSUE TITLE
Jde nastavit velikost mapy?

### ISSUE THREAD

**Issue by fan1x** [JanKleprlik/Zeleznice#3]

**Comment by JanKleprlik** [comment]
Velikost mapy jsem nejdříve nastavitelnou měl. Když se ale nastavila jiná velikost, než která je teď, tak se mi to nelíbilo (bylo to takový neuplný). A když se nastavila větší velikost, než která je teď, tak se vykreslila jen část mapy a po zvětšení okénka se ještě posunulo všechno co už bylo vykreslený. Takže jsem udělal kompromis a nastavil fixní velikost.

**Comment by fan1x** [comment]
Bylo by hezké, kdyby to bylo možné nastavit na začátku. Třeba s upozorněním, že se nemá zvětšovat okénko, že to může rozbít vykreslování... Ale není to potřeba dodělávat, jen kdybys měl chuť :)
