### ISSUE TITLE
Konzistentni pojmenovavani

### ISSUE THREAD

**Issue by fan1x** [JanKleprlik/Zeleznice#4]
https://github.com/JanKleprlik/Zeleznice/blob/e7d38ac857344bb89b3dfae64448c101a26b1dd1/Zeleznice.pas#L14

Nektere nazvy jsou `CamelCasem`, nektere jsou `camelcasem`

**Comment by JanKleprlik** [comment]
hotovo, předělané na camelcase

**Comment by fan1x** [comment]
A je to určitě všechno pushnuté/opravené? Viz https://github.com/JanKleprlik/Zeleznice/blob/529ac90ef2be01b9f3685e5794ea7903ba2a721e/Zeleznice.pas#L16

**Comment by JanKleprlik** [comment]
Dodělal jsem u všeho ještě podtržítka. Teď jsem je tam měl jen tam kde se mi to špatně četlo, ale asi je to lepší mít pro úplnost a jednotnost všude.
