### ISSUE TITLE
Pouzivej bud ceske nebo anglicke nazvy, ne kombinaci

### ISSUE THREAD

**Issue by fan1x** [JanKleprlik/Zeleznice#5]
https://github.com/JanKleprlik/Zeleznice/blob/e7d38ac857344bb89b3dfae64448c101a26b1dd1/Zeleznice.pas#L366

Rozhodni se pro jeden jazyk a ten potom pouzivej :)

**Comment by JanKleprlik** [comment]
hotovo, předělané do češtiny
